const buildProgramStructure = (days: Array<{
    title: string;
    warmup?: string;
    cooldown?: string;
    exercises: Array<{
        name: string;
        sets: number;
        reps: string;
        rest_seconds?: number;
        note?: string;
        video_url?: string;
    }>;
}>) => ({
    week_1: days.reduce<Record<string, unknown>>((acc, day, index) => {
        acc[`day_${index + 1}`] = day;
        return acc;
    }, {}),
});

export const MARKETPLACE_SELLERS = [
    {
        email: 'david.ng@demo.com',
        shop_name: 'David Physique Systems',
        shop_slug: 'david-physique-systems',
        shop_description: 'Shop giáo án, coaching bundle và service tối ưu body composition cho người tập trung vào tăng cơ, siết mỡ và prep sân khấu.',
        shop_logo_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1400&q=80',
        business_type: 'coach',
        contact_phone: '+84 912 345 003',
        contact_email: 'shop+david@gymerviet.demo',
        bank_info: {
            bank_name: 'Vietcombank',
            account_name: 'David Nguyen',
            account_number: '003912345678',
        },
        commission_rate: 8,
        is_verified: true,
        total_revenue: 248000000,
        total_orders: 214,
        avg_rating: 4.92,
        status: 'active',
    },
    {
        email: 'linh.pilates@demo.com',
        shop_name: 'Linh Pilates Studio',
        shop_slug: 'linh-pilates-studio',
        shop_description: 'Pilates, dinh dưỡng và các digital kit dành cho nữ văn phòng, sau sinh và người cần cải thiện posture.',
        shop_logo_url: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1400&q=80',
        business_type: 'coach',
        contact_phone: '+84 912 345 002',
        contact_email: 'shop+linh@gymerviet.demo',
        bank_info: {
            bank_name: 'Techcombank',
            account_name: 'Le Thuy Linh',
            account_number: '19034567890123',
        },
        commission_rate: 8,
        is_verified: true,
        total_revenue: 184000000,
        total_orders: 198,
        avg_rating: 4.88,
        status: 'active',
    },
    {
        email: 'hoang.cali@demo.com',
        shop_name: 'Hoang Cali Lab',
        shop_slug: 'hoang-cali-lab',
        shop_description: 'Phụ kiện bodyweight, mobility tools và gear tối giản cho người mê street workout và skill training.',
        shop_logo_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1400&q=80',
        business_type: 'coach',
        contact_phone: '+84 912 345 001',
        contact_email: 'shop+hoang@gymerviet.demo',
        bank_info: {
            bank_name: 'ACB',
            account_name: 'Phan Minh Hoang',
            account_number: '0192837465',
        },
        commission_rate: 8,
        is_verified: true,
        total_revenue: 129000000,
        total_orders: 156,
        avg_rating: 4.9,
        status: 'active',
    },
    {
        email: 'nhi.yoga@demo.com',
        shop_name: 'Nhi Yoga House',
        shop_slug: 'nhi-yoga-house',
        shop_description: 'Yoga wear, class props và các sản phẩm thiên về cảm giác mặc, thở và recovery nhẹ nhàng.',
        shop_logo_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=1400&q=80',
        business_type: 'coach',
        contact_phone: '+84 912 345 005',
        contact_email: 'shop+nhi@gymerviet.demo',
        bank_info: {
            bank_name: 'MB Bank',
            account_name: 'Nguyen Dieu Nhi',
            account_number: '0888123999',
        },
        commission_rate: 9,
        is_verified: true,
        total_revenue: 98000000,
        total_orders: 121,
        avg_rating: 4.87,
        status: 'active',
    },
    {
        email: 'huong.crossfit@demo.com',
        shop_name: 'Huong Hybrid Performance',
        shop_slug: 'huong-hybrid-performance',
        shop_description: 'Hybrid fitness, conditioning tools, summit ticket và supplement dành cho người tập cường độ cao.',
        shop_logo_url: 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1400&q=80',
        business_type: 'coach',
        contact_phone: '+84 912 345 006',
        contact_email: 'shop+huong@gymerviet.demo',
        bank_info: {
            bank_name: 'VPBank',
            account_name: 'Mai Thi Huong',
            account_number: '0977123456',
        },
        commission_rate: 8,
        is_verified: true,
        total_revenue: 141000000,
        total_orders: 168,
        avg_rating: 4.86,
        status: 'active',
    },
    {
        email: 'an.forge@demo.com',
        shop_name: 'Forge House Pro Shop',
        shop_slug: 'forge-house-pro-shop',
        shop_description: 'Merch, equipment, supplement và gear chọn theo tiêu chí tập thực chiến cho hội viên của Forge House.',
        shop_logo_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1400&q=80',
        business_type: 'gym',
        contact_phone: '+84 901 234 001',
        contact_email: 'proshop@forgehouse.demo',
        bank_info: {
            bank_name: 'BIDV',
            account_name: 'Forge House Gym',
            account_number: '2156789012',
        },
        commission_rate: 10,
        is_verified: true,
        total_revenue: 326000000,
        total_orders: 302,
        avg_rating: 4.84,
        status: 'active',
    },
    {
        email: 'thao.lotus@demo.com',
        shop_name: 'Lotus Flow Boutique',
        shop_slug: 'lotus-flow-boutique',
        shop_description: 'Membership, props và studio offers thiên về yoga, breathwork, mindfulness và class experience cao cấp.',
        shop_logo_url: 'https://images.unsplash.com/photo-1545208393-596371ba4d31?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1400&q=80',
        business_type: 'gym',
        contact_phone: '+84 901 234 005',
        contact_email: 'hello@lotusflow.demo',
        bank_info: {
            bank_name: 'Sacombank',
            account_name: 'Lotus Flow Studio',
            account_number: '060198765432',
        },
        commission_rate: 10,
        is_verified: true,
        total_revenue: 212000000,
        total_orders: 174,
        avg_rating: 4.91,
        status: 'active',
    },
    {
        email: 'reset.recovery@demo.com',
        shop_name: 'Reset Recovery Social Shop',
        shop_slug: 'reset-recovery-social-shop',
        shop_description: 'Recovery tools, hydration và body-care products cho dân tập nặng hoặc dân ngồi nhiều cần reset có chủ đích.',
        shop_logo_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80',
        shop_cover_url: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1400&q=80',
        business_type: 'gym',
        contact_phone: '+84 901 234 007',
        contact_email: 'shop@resetrecovery.demo',
        bank_info: {
            bank_name: 'TPBank',
            account_name: 'Reset Recovery Social',
            account_number: '0789123456',
        },
        commission_rate: 10,
        is_verified: true,
        total_revenue: 167000000,
        total_orders: 146,
        avg_rating: 4.89,
        status: 'active',
    },
];

export const MARKETPLACE_PRODUCTS: any[] = [
    {
        slug: 'shred-starter-8-week-blueprint',
        seller_email: 'david.ng@demo.com',
        category_slug: 'fat-loss-programs',
        title: 'Shred Starter 8-Week Blueprint',
        description: 'Giáo án siết mỡ 8 tuần cho người bận rộn muốn giảm mỡ nhưng vẫn giữ cơ. Bộ sản phẩm gồm lịch tập 4 buổi mỗi tuần, checklist ăn uống theo 3 mức calories, video sửa form cho 12 bài nền tảng và file check-in đo vòng eo từng tuần.',
        product_type: 'digital',
        price: 490000,
        compare_at_price: 690000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'DPS-SHRED-001',
        digital_file_url: 'https://downloads.gymerviet.demo/products/shred-starter-8-week-blueprint.zip',
        preview_content: 'Bạn nhận PDF 8 tuần, file meal guide 3 mức calories, 12 video form cơ bản và tracker check-in hằng tuần.',
        thumbnail_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&q=80',
            'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
            'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1200&q=80',
        ],
        attributes: {
            'Coach': 'David Nguyễn',
            'Mục tiêu': 'Giảm mỡ bền vững, vẫn giữ cảm giác tập khỏe',
            'Thời lượng': '8 tuần',
            'Tần suất': '4 buổi mỗi tuần',
            'Thiết bị cần': 'Dumbbell, bench, mini band, treadmill hoặc đi bộ ngoài trời',
            'Định dạng': 'PDF + video form + tracker',
        },
        tags: ['fat loss', 'beginner', 'body recomposition', 'meal guide'],
        view_count: 1820,
        sale_count: 134,
        wishlist_count: 92,
        featured_weight: 98,
        variants: [
            {
                variant_label: 'Lite · PDF',
                variant_attributes: { format: 'PDF', support: 'Tự học', access: 'Trọn đời' },
                price: 490000,
                compare_at_price: 690000,
                stock_quantity: null,
                sku: 'DPS-SHRED-LITE',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Standard · PDF + video',
                variant_attributes: { format: 'PDF + video', support: 'Checklist tuần', access: 'Trọn đời' },
                price: 690000,
                compare_at_price: 890000,
                stock_quantity: null,
                sku: 'DPS-SHRED-STD',
                image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Coach Check-in · 2 lần',
                variant_attributes: { format: 'PDF + video', support: '2 video check-in', access: '8 tuần' },
                price: 1190000,
                compare_at_price: 1490000,
                stock_quantity: 20,
                sku: 'DPS-SHRED-CHECKIN',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        training_package: {
            goal: 'fat_loss',
            level: 'beginner',
            duration_weeks: 8,
            sessions_per_week: 4,
            equipment_required: ['Dumbbell', 'Bench', 'Mini band'],
            includes_nutrition: true,
            includes_video: true,
            preview_weeks: 1,
            nutrition_guide: {
                calories: ['1600 kcal', '1800 kcal', '2000 kcal'],
                protein_target: '1.8g/kg bodyweight',
                notes: 'Ưu tiên bữa sáng giàu đạm, 1 refeed meal cuối tuần, 8.000–10.000 bước mỗi ngày.',
            },
            program_structure: buildProgramStructure([
                {
                    title: 'Lower Body + Steps',
                    warmup: '5 phút incline walk + hip opener',
                    cooldown: 'Thả lỏng đùi trước và hông 6 phút',
                    exercises: [
                        { name: 'Goblet squat', sets: 4, reps: '10-12', rest_seconds: 75 },
                        { name: 'Romanian deadlift', sets: 4, reps: '10', rest_seconds: 90 },
                        { name: 'Walking lunge', sets: 3, reps: '12 mỗi bên', rest_seconds: 60 },
                    ],
                },
                {
                    title: 'Upper Push Pull',
                    warmup: 'Band pull-apart + shoulder CARs',
                    cooldown: 'Lat stretch 4 phút',
                    exercises: [
                        { name: 'Incline dumbbell press', sets: 4, reps: '8-10', rest_seconds: 90 },
                        { name: 'One-arm row', sets: 4, reps: '10 mỗi bên', rest_seconds: 75 },
                        { name: 'Push-up mechanical drop set', sets: 3, reps: 'AMRAP', rest_seconds: 75 },
                    ],
                },
                {
                    title: 'Conditioning Intervals',
                    warmup: 'Dynamic mobility 6 phút',
                    cooldown: 'Walk chậm 5 phút',
                    exercises: [
                        { name: 'Treadmill intervals', sets: 8, reps: '40s nhanh / 80s chậm', rest_seconds: 0 },
                        { name: 'Battle rope finisher', sets: 5, reps: '20s on / 40s off', rest_seconds: 0 },
                    ],
                },
                {
                    title: 'Full Body Density',
                    warmup: 'Bodyweight circuit 5 phút',
                    cooldown: 'Foam roll 5 phút',
                    exercises: [
                        { name: 'Dumbbell thruster', sets: 4, reps: '12', rest_seconds: 75 },
                        { name: 'TRX row', sets: 4, reps: '12', rest_seconds: 60 },
                        { name: 'Step-up', sets: 3, reps: '14 mỗi bên', rest_seconds: 60 },
                    ],
                },
            ]),
        },
        reviews: [
            {
                athlete_email: 'tuan.vp@demo.com',
                rating: 5,
                comment: 'Rõ ràng, dễ theo và đặc biệt phần checklist ăn uống không gây áp lực. Sau 4 tuần mình xuống 2.8kg mà vẫn tập ổn.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
            {
                athlete_email: 'hau.gym@demo.com',
                rating: 4,
                comment: 'Hợp với người muốn siết lại nền tảng. Phần video form đủ chi tiết cho các bài cơ bản.',
                quality_rating: 4,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'lean-mass-12-week-system',
        seller_email: 'david.ng@demo.com',
        category_slug: 'muscle-gain-programs',
        title: 'Lean Mass 12-Week System',
        description: 'Program 12 tuần tăng cơ sạch cho người đã có nền tảng tập 6-12 tháng. Tài liệu tập trung vào progressive overload, kiểm soát volume theo tuần và meal template giúp tăng cân nhưng ít lên mỡ.',
        product_type: 'digital',
        price: 690000,
        compare_at_price: 890000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'DPS-BULK-012',
        digital_file_url: 'https://downloads.gymerviet.demo/products/lean-mass-12-week-system.zip',
        preview_content: 'Split 5 buổi, progression sheet, macro guide theo mức cân nặng và sample grocery list 7 ngày.',
        thumbnail_url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1200&q=80',
            'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
            'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=80',
        ],
        attributes: {
            'Coach': 'David Nguyễn',
            'Mục tiêu': 'Tăng cơ sạch, lên size nhưng ít tích mỡ',
            'Thời lượng': '12 tuần',
            'Split': 'Push / Pull / Legs / Upper / Lower',
            'Thiết bị cần': 'Gym đầy đủ máy và tạ',
            'Kèm dinh dưỡng': 'Macro guide + grocery template',
        },
        tags: ['muscle gain', 'hypertrophy', 'intermediate', 'progressive overload'],
        view_count: 1610,
        sale_count: 116,
        wishlist_count: 84,
        featured_weight: 93,
        variants: [
            {
                variant_label: 'Home Gym Adapted',
                variant_attributes: { setup: 'Dumbbell + bench', level: 'Intermediate', support: 'PDF' },
                price: 690000,
                compare_at_price: 890000,
                stock_quantity: null,
                sku: 'DPS-BULK-HOME',
                image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Full Gym',
                variant_attributes: { setup: 'Full machine + free weight gym', level: 'Intermediate', support: 'PDF + sheet' },
                price: 790000,
                compare_at_price: 990000,
                stock_quantity: null,
                sku: 'DPS-BULK-FULLGYM',
                image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Pro + 1 lần audit logbook',
                variant_attributes: { setup: 'Full gym', level: 'Intermediate+', support: 'PDF + audit' },
                price: 1490000,
                compare_at_price: 1790000,
                stock_quantity: 16,
                sku: 'DPS-BULK-PRO',
                image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        training_package: {
            goal: 'muscle_gain',
            level: 'intermediate',
            duration_weeks: 12,
            sessions_per_week: 5,
            equipment_required: ['Barbell', 'Dumbbell', 'Cable machine', 'Leg press'],
            includes_nutrition: true,
            includes_video: true,
            preview_weeks: 1,
            nutrition_guide: {
                surplus_target: '+220 đến +320 kcal mỗi ngày',
                protein_target: '2.0g/kg bodyweight',
                carb_focus: 'Ưu tiên carb quanh buổi tập và bữa tối sau chân lưng',
            },
            program_structure: buildProgramStructure([
                {
                    title: 'Push Strength Bias',
                    warmup: 'Band shoulder flow + 2 sets ramp up',
                    exercises: [
                        { name: 'Barbell bench press', sets: 5, reps: '5-6', rest_seconds: 150 },
                        { name: 'Incline dumbbell press', sets: 4, reps: '8-10', rest_seconds: 90 },
                        { name: 'Cable lateral raise', sets: 4, reps: '14-16', rest_seconds: 45 },
                    ],
                },
                {
                    title: 'Pull Width + Thickness',
                    warmup: 'Scap pull + lat activation 5 phút',
                    exercises: [
                        { name: 'Weighted pull-up', sets: 5, reps: '5-6', rest_seconds: 150 },
                        { name: 'Chest supported row', sets: 4, reps: '8-10', rest_seconds: 90 },
                        { name: 'Cable curl', sets: 3, reps: '12-14', rest_seconds: 60 },
                    ],
                },
                {
                    title: 'Legs Hypertrophy',
                    warmup: 'Bike 5 phút + ankle mobility',
                    exercises: [
                        { name: 'Back squat', sets: 5, reps: '6-8', rest_seconds: 150 },
                        { name: 'Romanian deadlift', sets: 4, reps: '8-10', rest_seconds: 120 },
                        { name: 'Leg extension', sets: 3, reps: '15-20', rest_seconds: 45 },
                    ],
                },
            ]),
        },
        reviews: [
            {
                athlete_email: 'hau.gym@demo.com',
                rating: 5,
                comment: 'Logbook và progression sheet rất đáng tiền. Mình tăng 1.7kg trong 5 tuần mà form vẫn ổn.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
            {
                athlete_email: 'tam.cut@demo.com',
                rating: 4,
                comment: 'Volume được chia hợp lý, không bị quá tải. Phiên bản home gym adapt khá ổn cho ai chưa có full setup.',
                quality_rating: 4,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'peak-week-ready-protocol',
        seller_email: 'david.ng@demo.com',
        category_slug: 'competition-prep',
        title: 'Peak Week Ready Protocol',
        description: 'Bộ protocol 6 tuần trước sân khấu dành cho người đã có coach nền hoặc tự prep ở giai đoạn cuối. Sản phẩm tập trung vào depletion / load, posing checklist, sodium-water notes và file theo dõi ảnh front side back.',
        product_type: 'digital',
        price: 990000,
        compare_at_price: 1490000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'DPS-PEAK-006',
        digital_file_url: 'https://downloads.gymerviet.demo/products/peak-week-ready-protocol.zip',
        preview_content: 'Bao gồm posing checklist, checklist sodium-water, template peak week và guideline check-in ảnh.',
        thumbnail_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
            'https://images.unsplash.com/photo-1534367610401-9f5ed68180aa?w=1200&q=80',
            'https://images.unsplash.com/photo-1594737625785-cb10d637f2c4?w=1200&q=80',
        ],
        attributes: {
            'Coach': 'David Nguyễn',
            'Mục tiêu': 'Giai đoạn cuối prep thi đấu',
            'Thời lượng': '6 tuần',
            'Posing': 'Checklist front / side / back + transition',
            'Kèm biểu mẫu': 'Peak week tracker + photo check-in',
            'Đối tượng': 'Advanced, đã có nền tập và ăn prep trước đó',
        },
        tags: ['competition prep', 'mens physique', 'classic physique', 'advanced'],
        view_count: 980,
        sale_count: 42,
        wishlist_count: 40,
        featured_weight: 85,
        variants: [
            {
                variant_label: 'Men’s Physique Track',
                variant_attributes: { division: 'Men’s Physique', support: 'PDF + posing cues', duration: '6 tuần' },
                price: 990000,
                compare_at_price: 1490000,
                stock_quantity: null,
                sku: 'DPS-PEAK-MP',
                image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Classic Physique Track',
                variant_attributes: { division: 'Classic Physique', support: 'PDF + posing cues', duration: '6 tuần' },
                price: 1090000,
                compare_at_price: 1590000,
                stock_quantity: null,
                sku: 'DPS-PEAK-CP',
                image_url: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Prep Audit + 1 call',
                variant_attributes: { division: 'Any physique class', support: 'PDF + 1 Zoom call', duration: '6 tuần' },
                price: 2190000,
                compare_at_price: 2590000,
                stock_quantity: 10,
                sku: 'DPS-PEAK-AUDIT',
                image_url: 'https://images.unsplash.com/photo-1534367610401-9f5ed68180aa?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        training_package: {
            goal: 'competition_prep',
            level: 'advanced',
            duration_weeks: 6,
            sessions_per_week: 6,
            equipment_required: ['Full gym setup', 'Phone camera', 'Posing mirror'],
            includes_nutrition: true,
            includes_video: true,
            preview_weeks: 1,
            nutrition_guide: {
                focus: 'Water-sodium consistency, depletion days, controlled carb load',
                warning: 'Không áp dụng nếu chưa có nền prep ổn định hoặc có vấn đề sức khỏe.',
            },
            program_structure: buildProgramStructure([
                {
                    title: 'Depletion A',
                    warmup: 'Stepper 8 phút + activation',
                    exercises: [
                        { name: 'Leg press constant tension', sets: 4, reps: '18-20', rest_seconds: 60 },
                        { name: 'Cable fly', sets: 4, reps: '16-18', rest_seconds: 45 },
                        { name: 'Lat pulldown wide', sets: 4, reps: '16-18', rest_seconds: 45 },
                    ],
                },
                {
                    title: 'Depletion B',
                    warmup: 'Bike nhẹ 6 phút',
                    exercises: [
                        { name: 'Smith hack squat', sets: 4, reps: '15-18', rest_seconds: 60 },
                        { name: 'Machine shoulder press', sets: 4, reps: '14-16', rest_seconds: 45 },
                        { name: 'Cable curl + rope pushdown', sets: 3, reps: '15-18', rest_seconds: 30 },
                    ],
                },
                {
                    title: 'Pump + Posing',
                    warmup: 'Band circuit 5 phút',
                    exercises: [
                        { name: 'Pump circuit upper body', sets: 5, reps: '45s each station', rest_seconds: 30 },
                        { name: 'Mandatory posing rounds', sets: 6, reps: '60s hold', rest_seconds: 30 },
                    ],
                },
            ]),
        },
        reviews: [
            {
                athlete_email: 'hau.gym@demo.com',
                rating: 5,
                comment: 'Phần checklist peak week cực hữu ích. Mình dùng để phối với coach chính và tránh bị loạn thông tin.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'mobility-reset-28-day-flow',
        seller_email: 'linh.pilates@demo.com',
        category_slug: 'flexibility-programs',
        title: 'Mobility Reset 28-Day Flow',
        description: 'Lộ trình 28 ngày cho dân văn phòng, runner hoặc người tập tạ bị cứng vai hông lưng. Mỗi buổi 20-35 phút, tập trung vào nhịp thở, thoracic rotation, hip opener và ankle mobility để body feel nhẹ ngay từ tuần đầu.',
        product_type: 'digital',
        price: 390000,
        compare_at_price: 590000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'LPS-MOB-028',
        digital_file_url: 'https://downloads.gymerviet.demo/products/mobility-reset-28-day-flow.zip',
        preview_content: '4 tuần mobility flow với video demo, timer sheet và office reset routine 12 phút.',
        thumbnail_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=1200&q=80',
            'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80',
            'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&q=80',
        ],
        attributes: {
            'Coach': 'Lê Thuỳ Linh',
            'Mục tiêu': 'Mở vai, hông, cột sống ngực và giảm cảm giác ì sau giờ ngồi lâu',
            'Thời lượng': '28 ngày',
            'Thời gian mỗi buổi': '20-35 phút',
            'Thiết bị cần': 'Mat, mini band, yoga block nếu có',
            'Phù hợp': 'All level',
        },
        tags: ['mobility', 'posture', 'office reset', 'pilates flow'],
        view_count: 1430,
        sale_count: 119,
        wishlist_count: 71,
        featured_weight: 90,
        variants: [
            {
                variant_label: 'Mat Only',
                variant_attributes: { setup: 'Chỉ cần mat', support: 'PDF + timer', duration: '28 ngày' },
                price: 390000,
                compare_at_price: 590000,
                stock_quantity: null,
                sku: 'LPS-MOB-MAT',
                image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Mat + Mini Band',
                variant_attributes: { setup: 'Mat + mini band', support: 'PDF + video', duration: '28 ngày' },
                price: 490000,
                compare_at_price: 690000,
                stock_quantity: null,
                sku: 'LPS-MOB-BAND',
                image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Office Reset Pack',
                variant_attributes: { setup: 'Mat + mini band + chair drills', support: 'PDF + video + desk flow', duration: '28 ngày' },
                price: 690000,
                compare_at_price: 890000,
                stock_quantity: 30,
                sku: 'LPS-MOB-OFFICE',
                image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        training_package: {
            goal: 'flexibility',
            level: 'all',
            duration_weeks: 4,
            sessions_per_week: 5,
            equipment_required: ['Mat', 'Mini band'],
            includes_nutrition: false,
            includes_video: true,
            preview_weeks: 1,
            nutrition_guide: {
                note: 'Không có meal plan riêng, nhưng có hydration cue và nhắc thở bụng trước giờ ngủ.',
            },
            program_structure: buildProgramStructure([
                {
                    title: 'Shoulder + Neck Reset',
                    warmup: 'Box breathing 2 phút',
                    cooldown: 'Supine twist 3 phút',
                    exercises: [
                        { name: 'Wall slide', sets: 3, reps: '12', rest_seconds: 30 },
                        { name: 'Thread the needle', sets: 3, reps: '8 mỗi bên', rest_seconds: 20 },
                        { name: 'Band pull-apart slow tempo', sets: 3, reps: '15', rest_seconds: 30 },
                    ],
                },
                {
                    title: 'Hip Opening Flow',
                    warmup: '90/90 breathing 2 phút',
                    cooldown: 'Pigeon stretch 3 phút',
                    exercises: [
                        { name: '90/90 hip switch', sets: 3, reps: '10 mỗi bên', rest_seconds: 20 },
                        { name: 'Cossack squat assisted', sets: 3, reps: '8 mỗi bên', rest_seconds: 30 },
                        { name: 'Frog rock', sets: 3, reps: '12', rest_seconds: 20 },
                    ],
                },
                {
                    title: 'Thoracic Flow',
                    warmup: 'Cat cow 90 giây',
                    exercises: [
                        { name: 'Open book', sets: 3, reps: '10 mỗi bên', rest_seconds: 20 },
                        { name: 'Bench thoracic opener', sets: 3, reps: '45s giữ', rest_seconds: 20 },
                        { name: 'Bear position reach', sets: 3, reps: '8 mỗi bên', rest_seconds: 30 },
                    ],
                },
            ]),
        },
        reviews: [
            {
                athlete_email: 'an.yoga@demo.com',
                rating: 5,
                comment: 'Cảm giác nhẹ người ngay từ tuần đầu. Phần office reset 12 phút rất hợp dân ngồi máy tính.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
            {
                athlete_email: 'ngoc.run@demo.com',
                rating: 4,
                comment: 'Runner dùng để mở hông và cổ chân rất ổn. Mình thích vì mỗi flow không quá dài.',
                quality_rating: 4,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'macro-reset-30-day-meal-plan',
        seller_email: 'linh.pilates@demo.com',
        category_slug: 'meal-plans',
        title: 'Macro Reset 30-Day Meal Plan',
        description: 'Meal plan 30 ngày dành cho người muốn ăn lành mạnh nhưng vẫn thực tế với nhịp sống công sở. Có shopping list theo tuần, meal prep guide 90 phút Chủ nhật và phiên bản vegetarian.',
        product_type: 'digital',
        price: 320000,
        compare_at_price: 450000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'LPS-MEAL-030',
        digital_file_url: 'https://downloads.gymerviet.demo/products/macro-reset-30-day-meal-plan.pdf',
        preview_content: '4 tuần thực đơn, macro sheet, grocery list, thay thế món Việt và 10 món meal prep nhanh dưới 20 phút.',
        thumbnail_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&q=80',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80',
            'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&q=80',
        ],
        attributes: {
            'Tác giả': 'Lê Thuỳ Linh',
            'Thời lượng': '30 ngày',
            'Cấu trúc': '4 tuần meal plan + shopping list + prep guide',
            'Phong cách': 'Linh hoạt, dễ áp dụng với món Việt',
            'Đối tượng': 'Giảm mỡ nhẹ, giữ cân hoặc lifestyle healthy',
            'File nhận được': 'PDF + macro sheet',
        },
        tags: ['meal plan', 'macro tracking', 'office worker', 'healthy food'],
        view_count: 1260,
        sale_count: 108,
        wishlist_count: 65,
        featured_weight: 82,
        variants: [
            {
                variant_label: '1600 kcal · Cut',
                variant_attributes: { calories: '1600 kcal', style: 'High protein', meals: '3 bữa chính + 1 snack' },
                price: 320000,
                compare_at_price: 450000,
                stock_quantity: null,
                sku: 'LPS-MEAL-1600',
                image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: '1900 kcal · Balance',
                variant_attributes: { calories: '1900 kcal', style: 'Balanced', meals: '3 bữa chính + 2 snack' },
                price: 340000,
                compare_at_price: 470000,
                stock_quantity: null,
                sku: 'LPS-MEAL-1900',
                image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Vegetarian 1800 kcal',
                variant_attributes: { calories: '1800 kcal', style: 'Vegetarian', meals: '3 bữa chính + 1 snack' },
                price: 360000,
                compare_at_price: 490000,
                stock_quantity: null,
                sku: 'LPS-MEAL-VEG',
                image_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Family Prep 2200 kcal',
                variant_attributes: { calories: '2200 kcal', style: 'Meal prep cho 2 người', meals: 'Combo nấu 2 ngày/lần' },
                price: 420000,
                compare_at_price: 560000,
                stock_quantity: null,
                sku: 'LPS-MEAL-FAM',
                image_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
        ],
        reviews: [
            {
                athlete_email: 'tuan.vp@demo.com',
                rating: 5,
                comment: 'Shopping list rất thực tế, meal prep Chủ nhật 90 phút đúng như mô tả. Dễ theo hơn nhiều meal plan mình từng mua.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'forge-house-oversized-performance-tee',
        seller_email: 'an.forge@demo.com',
        category_slug: 'gym-wear',
        title: 'Forge House Oversized Performance Tee',
        description: 'Áo tập form oversized vừa đủ, chất vải dry-touch, rơi vai đẹp nhưng không quá dày. Dùng được cho buổi push day, cardio nhẹ hoặc mặc đi cafe sau tập.',
        product_type: 'physical',
        price: 320000,
        compare_at_price: 390000,
        currency: 'VND',
        stock_quantity: 84,
        track_inventory: true,
        sku: 'FHP-TEE-OS',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=1200&q=80',
            'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&q=80',
            'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=1200&q=80',
        ],
        attributes: {
            'Chất liệu': '88% polyester, 12% spandex',
            'Form': 'Oversized, drop shoulder',
            'Cảm giác mặc': 'Mềm, khô nhanh, ít bám mồ hôi',
            'Phù hợp': 'Gym, mobility, daily wear',
            'Hướng dẫn giặt': 'Giặt lạnh, không sấy nóng',
            'In logo': 'Forge House nhỏ ở ngực trái + print sau lưng',
        },
        tags: ['gym wear', 'oversized tee', 'quick dry', 'forge house'],
        view_count: 890,
        sale_count: 64,
        wishlist_count: 38,
        featured_weight: 78,
        variants: [
            {
                variant_label: 'Black · M',
                variant_attributes: { color: 'Black', size: 'M', fit: 'Oversized' },
                price: 320000,
                compare_at_price: 390000,
                stock_quantity: 12,
                sku: 'FHP-TEE-BLK-M',
                image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Black · L',
                variant_attributes: { color: 'Black', size: 'L', fit: 'Oversized' },
                price: 320000,
                compare_at_price: 390000,
                stock_quantity: 14,
                sku: 'FHP-TEE-BLK-L',
                image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Black · XL',
                variant_attributes: { color: 'Black', size: 'XL', fit: 'Oversized' },
                price: 320000,
                compare_at_price: 390000,
                stock_quantity: 10,
                sku: 'FHP-TEE-BLK-XL',
                image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Sand · M',
                variant_attributes: { color: 'Sand', size: 'M', fit: 'Oversized' },
                price: 340000,
                compare_at_price: 410000,
                stock_quantity: 13,
                sku: 'FHP-TEE-SAND-M',
                image_url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
            {
                variant_label: 'Sand · L',
                variant_attributes: { color: 'Sand', size: 'L', fit: 'Oversized' },
                price: 340000,
                compare_at_price: 410000,
                stock_quantity: 16,
                sku: 'FHP-TEE-SAND-L',
                image_url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80',
                is_active: true,
                sort_order: 4,
            },
            {
                variant_label: 'Sand · XL',
                variant_attributes: { color: 'Sand', size: 'XL', fit: 'Oversized' },
                price: 340000,
                compare_at_price: 410000,
                stock_quantity: 9,
                sku: 'FHP-TEE-SAND-XL',
                image_url: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80',
                is_active: true,
                sort_order: 5,
            },
        ],
        reviews: [
            {
                athlete_email: 'khoa.demo@demo.com',
                rating: 5,
                comment: 'Form lên đẹp hơn kỳ vọng, mặc squat và deadlift đều thoải mái. Vải khô nhanh sau buổi WOD.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'flowform-seamless-yoga-set',
        seller_email: 'nhi.yoga@demo.com',
        category_slug: 'yoga-wear',
        title: 'FlowForm Seamless Yoga Set',
        description: 'Set bra + legging cạp cao dành cho yoga, pilates và low-impact training. Chất vải co giãn 4 chiều, nén vừa đủ, không lộ đường may và lên màu rất dịu.',
        product_type: 'physical',
        price: 590000,
        compare_at_price: 740000,
        currency: 'VND',
        stock_quantity: 66,
        track_inventory: true,
        sku: 'NYH-SET-001',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80',
            'https://images.unsplash.com/photo-1549576490-b0b4831ef60a?w=1200&q=80',
            'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&q=80',
        ],
        attributes: {
            'Material': 'Nylon seamless + elastane',
            'Độ nén': 'Medium support',
            'Hoạt động phù hợp': 'Yoga, Pilates, stretching, walk nhẹ',
            'Waistband': 'High-rise, không cuộn mép',
            'Chăm sóc': 'Giặt túi lưới, không dùng nước xả đậm đặc',
        },
        tags: ['yoga wear', 'pilates set', 'seamless', 'high waist'],
        view_count: 940,
        sale_count: 58,
        wishlist_count: 51,
        featured_weight: 80,
        variants: [
            {
                variant_label: 'Sage · S',
                variant_attributes: { color: 'Sage', size: 'S', support: 'Medium' },
                price: 590000,
                compare_at_price: 740000,
                stock_quantity: 10,
                sku: 'NYH-SET-SAGE-S',
                image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Sage · M',
                variant_attributes: { color: 'Sage', size: 'M', support: 'Medium' },
                price: 590000,
                compare_at_price: 740000,
                stock_quantity: 12,
                sku: 'NYH-SET-SAGE-M',
                image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Sage · L',
                variant_attributes: { color: 'Sage', size: 'L', support: 'Medium' },
                price: 590000,
                compare_at_price: 740000,
                stock_quantity: 8,
                sku: 'NYH-SET-SAGE-L',
                image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Plum · S',
                variant_attributes: { color: 'Plum', size: 'S', support: 'Medium' },
                price: 620000,
                compare_at_price: 760000,
                stock_quantity: 9,
                sku: 'NYH-SET-PLUM-S',
                image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
            {
                variant_label: 'Plum · M',
                variant_attributes: { color: 'Plum', size: 'M', support: 'Medium' },
                price: 620000,
                compare_at_price: 760000,
                stock_quantity: 14,
                sku: 'NYH-SET-PLUM-M',
                image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
                is_active: true,
                sort_order: 4,
            },
            {
                variant_label: 'Plum · L',
                variant_attributes: { color: 'Plum', size: 'L', support: 'Medium' },
                price: 620000,
                compare_at_price: 760000,
                stock_quantity: 13,
                sku: 'NYH-SET-PLUM-L',
                image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
                is_active: true,
                sort_order: 5,
            },
        ],
        reviews: [
            {
                athlete_email: 'an.yoga@demo.com',
                rating: 5,
                comment: 'Mặc rất ôm nhưng không khó thở. Tập vinyasa hoặc pilates đều thấy thoải mái.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'carbon-lift-trainer-2',
        seller_email: 'an.forge@demo.com',
        category_slug: 'footwear',
        title: 'Carbon Lift Trainer 2',
        description: 'Đôi trainer đế phẳng, khóa dây chắc và upper ôm bàn chân vừa đủ cho squat, hinge, machine day hoặc cardio ngắn. Dành cho người muốn một đôi all-round thiên strength.',
        product_type: 'physical',
        price: 1890000,
        compare_at_price: 2390000,
        currency: 'VND',
        stock_quantity: 48,
        track_inventory: true,
        sku: 'FHP-SHOE-CLT2',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&q=80',
            'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=1200&q=80',
            'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&q=80',
        ],
        attributes: {
            'Heel drop': '4 mm',
            'Upper': 'Breathable mesh + support cage',
            'Best use': 'Strength day, machine day, conditioning vừa phải',
            'Đế': 'Gum outsole bám sàn',
            'Fit': 'True to size, hơi ôm phần mid-foot',
        },
        tags: ['training shoes', 'lifting shoes', 'strength', 'cross-training'],
        view_count: 1110,
        sale_count: 49,
        wishlist_count: 57,
        featured_weight: 76,
        variants: [
            {
                variant_label: 'Stone Grey · 39',
                variant_attributes: { color: 'Stone Grey', size: '39', fit: 'True to size' },
                price: 1890000,
                compare_at_price: 2390000,
                stock_quantity: 5,
                sku: 'FHP-CLT2-39',
                image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Stone Grey · 40',
                variant_attributes: { color: 'Stone Grey', size: '40', fit: 'True to size' },
                price: 1890000,
                compare_at_price: 2390000,
                stock_quantity: 9,
                sku: 'FHP-CLT2-40',
                image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Stone Grey · 41',
                variant_attributes: { color: 'Stone Grey', size: '41', fit: 'True to size' },
                price: 1890000,
                compare_at_price: 2390000,
                stock_quantity: 11,
                sku: 'FHP-CLT2-41',
                image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Stone Grey · 42',
                variant_attributes: { color: 'Stone Grey', size: '42', fit: 'True to size' },
                price: 1890000,
                compare_at_price: 2390000,
                stock_quantity: 8,
                sku: 'FHP-CLT2-42',
                image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
            {
                variant_label: 'Midnight Black · 41',
                variant_attributes: { color: 'Midnight Black', size: '41', fit: 'True to size' },
                price: 1990000,
                compare_at_price: 2490000,
                stock_quantity: 7,
                sku: 'FHP-CLT2-BLK-41',
                image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
                is_active: true,
                sort_order: 4,
            },
            {
                variant_label: 'Midnight Black · 42',
                variant_attributes: { color: 'Midnight Black', size: '42', fit: 'True to size' },
                price: 1990000,
                compare_at_price: 2490000,
                stock_quantity: 8,
                sku: 'FHP-CLT2-BLK-42',
                image_url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80',
                is_active: true,
                sort_order: 5,
            },
        ],
        reviews: [
            {
                athlete_email: 'tam.cut@demo.com',
                rating: 4,
                comment: 'Đế khá ổn cho squat và machine day. Không thay thế hoàn toàn lifting shoes chuyên dụng nhưng all-round rất tốt.',
                quality_rating: 4,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'versagrip-wrist-wrap-pro',
        seller_email: 'hoang.cali@demo.com',
        category_slug: 'accessories',
        title: 'VersaGrip Wrist Wrap Pro',
        description: 'Bộ wrist wrap + grip pad 2 trong 1 cho pull day, handstand prep, calisthenics hoặc tập upper cần ổn định cổ tay tốt hơn. Chất bám không quá cứng, đeo lâu không cấn.',
        product_type: 'physical',
        price: 290000,
        compare_at_price: 360000,
        currency: 'VND',
        stock_quantity: 96,
        track_inventory: true,
        sku: 'HCL-WRAP-002',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
            'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=1200&q=80',
            'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=1200&q=80&sat=-30',
        ],
        attributes: {
            'Chiều dài': '45 cm',
            'Độ cứng': 'Medium support',
            'Phù hợp': 'Pull day, handstand drill, front rack support',
            'Chất liệu': 'Cotton blend + anti-slip patch',
            'Bảo quản': 'Phơi khô sau buổi tập, không ngâm quá lâu',
        },
        tags: ['wrist wrap', 'grip support', 'calisthenics', 'accessories'],
        view_count: 760,
        sale_count: 88,
        wishlist_count: 31,
        featured_weight: 74,
        variants: [
            {
                variant_label: 'Black · S/M',
                variant_attributes: { color: 'Black', size: 'S/M', support: 'Medium' },
                price: 290000,
                compare_at_price: 360000,
                stock_quantity: 24,
                sku: 'HCL-WRAP-BLK-SM',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Black · L/XL',
                variant_attributes: { color: 'Black', size: 'L/XL', support: 'Medium' },
                price: 290000,
                compare_at_price: 360000,
                stock_quantity: 22,
                sku: 'HCL-WRAP-BLK-LXL',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Stone · S/M',
                variant_attributes: { color: 'Stone', size: 'S/M', support: 'Medium' },
                price: 310000,
                compare_at_price: 380000,
                stock_quantity: 18,
                sku: 'HCL-WRAP-STN-SM',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Stone · L/XL',
                variant_attributes: { color: 'Stone', size: 'L/XL', support: 'Medium' },
                price: 310000,
                compare_at_price: 380000,
                stock_quantity: 20,
                sku: 'HCL-WRAP-STN-LXL',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
        ],
        reviews: [
            {
                athlete_email: 'khoa.demo@demo.com',
                rating: 5,
                comment: 'Wrap ôm gọn, hỗ trợ cổ tay tốt mà vẫn dễ chuyển sang pull-up hoặc dip set liên tục.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'urban-gym-duffel-35l',
        seller_email: 'an.forge@demo.com',
        category_slug: 'bags',
        title: 'Urban Gym Duffel 35L',
        description: 'Túi gym 35L có ngăn giày riêng, ngăn ướt chống nước nhẹ và dây đeo vai dày hơn mặt bằng chung. Dùng tốt cho người đi gym trước giờ làm hoặc cuối ngày muốn bỏ đủ shoes, belt, shaker và khăn.',
        product_type: 'physical',
        price: 780000,
        compare_at_price: 920000,
        currency: 'VND',
        stock_quantity: 52,
        track_inventory: true,
        sku: 'FHP-BAG-35L',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1542291026-1534438327276?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1542291026-1534438327276?w=1200&q=80',
            'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80',
            'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=1200&q=80',
        ],
        attributes: {
            'Dung tích': '35L / 45L',
            'Ngăn phụ': 'Ngăn giày riêng + ngăn đồ ướt',
            'Chất liệu': 'Nylon ripstop chống nước nhẹ',
            'Phù hợp': 'Gym, du lịch ngắn ngày, class studio',
            'Quai đeo': 'Shoulder strap bản lớn có pad',
        },
        tags: ['gym bag', 'duffel', 'shoe compartment', 'daily carry'],
        view_count: 690,
        sale_count: 41,
        wishlist_count: 29,
        featured_weight: 70,
        variants: [
            {
                variant_label: 'Black · 35L',
                variant_attributes: { color: 'Black', size: '35L', compartments: 'Standard' },
                price: 780000,
                compare_at_price: 920000,
                stock_quantity: 13,
                sku: 'FHP-BAG-BLK-35',
                image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Moss · 35L',
                variant_attributes: { color: 'Moss', size: '35L', compartments: 'Standard' },
                price: 780000,
                compare_at_price: 920000,
                stock_quantity: 11,
                sku: 'FHP-BAG-MOSS-35',
                image_url: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Black · 45L',
                variant_attributes: { color: 'Black', size: '45L', compartments: 'Extra shoe pocket' },
                price: 860000,
                compare_at_price: 990000,
                stock_quantity: 15,
                sku: 'FHP-BAG-BLK-45',
                image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Stone · 45L',
                variant_attributes: { color: 'Stone', size: '45L', compartments: 'Extra shoe pocket' },
                price: 860000,
                compare_at_price: 990000,
                stock_quantity: 13,
                sku: 'FHP-BAG-STN-45',
                image_url: 'https://images.unsplash.com/photo-1542291026-1534438327276?w=800&q=80',
                is_active: true,
                sort_order: 3,
            },
        ],
        reviews: [
            {
                athlete_email: 'tuan.vp@demo.com',
                rating: 4,
                comment: 'Ngăn giày riêng rất tiện. Form túi gọn, đi làm rồi ghé gym không bị quá cồng kềnh.',
                quality_rating: 4,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'clean-whey-isolate-2kg',
        seller_email: 'an.forge@demo.com',
        category_slug: 'whey-protein',
        title: 'Clean Whey Isolate 2kg',
        description: 'Whey isolate vị vừa miệng, ít gắt ngọt và pha tan nhanh. Mỗi serving 25g protein, lactose thấp, hợp cho người đang siết hoặc cần source protein gọn sau tập.',
        product_type: 'physical',
        price: 1480000,
        compare_at_price: 1690000,
        currency: 'VND',
        stock_quantity: 60,
        track_inventory: true,
        sku: 'FHP-WHEY-2KG',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1579722821273-0f6c1d44362f?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&q=80',
            'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=1200&q=80',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&q=80',
        ],
        attributes: {
            'Protein / serving': '25g',
            'Carb': '2g',
            'Fat': '1.5g',
            'Phù hợp': 'Post-workout, bữa phụ, siết hoặc giữ dáng',
            'Thông tin thêm': 'Lactose thấp, dễ pha tan',
            'Khối lượng': '2kg',
        },
        tags: ['whey isolate', 'protein', 'post workout', 'supplement'],
        view_count: 1340,
        sale_count: 97,
        wishlist_count: 64,
        featured_weight: 88,
        variants: [
            {
                variant_label: 'Vanilla Bean · 2kg',
                variant_attributes: { flavor: 'Vanilla Bean', weight: '2kg', protein: '25g/serving' },
                price: 1480000,
                compare_at_price: 1690000,
                stock_quantity: 16,
                sku: 'FHP-WHEY-VAN',
                image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c1d44362f?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Dark Chocolate · 2kg',
                variant_attributes: { flavor: 'Dark Chocolate', weight: '2kg', protein: '25g/serving' },
                price: 1480000,
                compare_at_price: 1690000,
                stock_quantity: 18,
                sku: 'FHP-WHEY-CHOCO',
                image_url: 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Milk Tea · 2kg',
                variant_attributes: { flavor: 'Milk Tea', weight: '2kg', protein: '25g/serving' },
                price: 1510000,
                compare_at_price: 1720000,
                stock_quantity: 14,
                sku: 'FHP-WHEY-MILKTEA',
                image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Matcha Latte · 2kg',
                variant_attributes: { flavor: 'Matcha Latte', weight: '2kg', protein: '25g/serving' },
                price: 1510000,
                compare_at_price: 1720000,
                stock_quantity: 12,
                sku: 'FHP-WHEY-MATCHA',
                image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c1d44362f?w=800&q=80&sat=-20',
                is_active: true,
                sort_order: 3,
            },
        ],
        reviews: [
            {
                athlete_email: 'hau.gym@demo.com',
                rating: 5,
                comment: 'Vị chocolate khá sạch, không quá ngọt. Pha với nước vẫn dễ uống sau tập nặng.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'micronized-creatine-monohydrate',
        seller_email: 'huong.crossfit@demo.com',
        category_slug: 'creatine',
        title: 'Micronized Creatine Monohydrate',
        description: 'Creatine monohydrate micronized vị neutral, dễ pha và ít lợn cợn hơn. Hợp cho người tập sức mạnh, hypertrophy hoặc hybrid muốn tối ưu phục hồi và output.',
        product_type: 'physical',
        price: 420000,
        compare_at_price: 520000,
        currency: 'VND',
        stock_quantity: 88,
        track_inventory: true,
        sku: 'HHP-CREA-001',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1579722821273-0f6c1d44362f?w=1200&q=80&sat=-40',
        gallery: [
            'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=1200&q=80&sat=-10',
            'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80',
            'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        ],
        attributes: {
            'Thành phần': '100% creatine monohydrate micronized',
            'Serving': '5g',
            'Khuyến nghị': 'Dùng mỗi ngày, không cần cycle',
            'Phù hợp': 'Strength, hypertrophy, CrossFit, chạy cường độ cao',
            'Mixing': 'Tan tốt hơn khi lắc kỹ với nước ấm nhẹ',
        },
        tags: ['creatine', 'strength', 'recovery', 'performance'],
        view_count: 1020,
        sale_count: 84,
        wishlist_count: 43,
        featured_weight: 84,
        variants: [
            {
                variant_label: '300g Jar',
                variant_attributes: { weight: '300g', servings: '60', flavor: 'Unflavored' },
                price: 420000,
                compare_at_price: 520000,
                stock_quantity: 30,
                sku: 'HHP-CREA-300',
                image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c1d44362f?w=800&q=80&sat=-40',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: '500g Jar',
                variant_attributes: { weight: '500g', servings: '100', flavor: 'Unflavored' },
                price: 590000,
                compare_at_price: 690000,
                stock_quantity: 28,
                sku: 'HHP-CREA-500',
                image_url: 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&q=80&sat=-10',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: '1kg Refill Pack',
                variant_attributes: { weight: '1kg', servings: '200', flavor: 'Unflavored' },
                price: 990000,
                compare_at_price: 1180000,
                stock_quantity: 18,
                sku: 'HHP-CREA-1KG',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'khoa.demo@demo.com',
                rating: 5,
                comment: 'Pha dễ, uống mỗi ngày không khó chịu. Dạng refill 1kg tiết kiệm hơn nếu dùng dài hạn.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'electrolyte-hydration-sticks',
        seller_email: 'reset.recovery@demo.com',
        category_slug: 'hydration',
        title: 'Electrolyte Hydration Sticks',
        description: 'Gói điện giải dạng stick tiện bỏ balo hoặc túi gym. Hợp cho buổi tập nặng ra mồ hôi nhiều, sauna session hoặc ngày ngồi điều hòa khô người nhưng vẫn cần uống đủ nước.',
        product_type: 'physical',
        price: 265000,
        compare_at_price: 320000,
        currency: 'VND',
        stock_quantity: 110,
        track_inventory: true,
        sku: 'RRS-HYDR-015',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&q=80&sat=10',
        gallery: [
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80',
            'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&q=80',
            'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=1200&q=80',
        ],
        attributes: {
            'Sodium': '650mg / stick',
            'Potassium': '250mg / stick',
            'Công dụng': 'Hydration, recovery sau sauna, hỗ trợ tập cường độ cao',
            'Cách dùng': '1 stick với 500-700ml nước',
            'Không chứa': 'Đường tinh luyện',
        },
        tags: ['hydration', 'electrolyte', 'sauna', 'recovery'],
        view_count: 870,
        sale_count: 74,
        wishlist_count: 39,
        featured_weight: 79,
        variants: [
            {
                variant_label: 'Mixed Box · 15 sticks',
                variant_attributes: { flavor: 'Mixed', quantity: '15 sticks', use_case: 'Daily hydration' },
                price: 265000,
                compare_at_price: 320000,
                stock_quantity: 28,
                sku: 'RRS-HYDR-MIX15',
                image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Citrus Salt · 30 sticks',
                variant_attributes: { flavor: 'Citrus Salt', quantity: '30 sticks', use_case: 'Heavy training' },
                price: 460000,
                compare_at_price: 540000,
                stock_quantity: 25,
                sku: 'RRS-HYDR-CIT30',
                image_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Berry Chill · 30 sticks',
                variant_attributes: { flavor: 'Berry Chill', quantity: '30 sticks', use_case: 'Sauna + cardio' },
                price: 460000,
                compare_at_price: 540000,
                stock_quantity: 24,
                sku: 'RRS-HYDR-BER30',
                image_url: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
            {
                variant_label: 'Night Reset · 15 sticks',
                variant_attributes: { flavor: 'Lemon Calm', quantity: '15 sticks', use_case: 'Recovery tối' },
                price: 295000,
                compare_at_price: 350000,
                stock_quantity: 33,
                sku: 'RRS-HYDR-NIGHT15',
                image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&sat=10',
                is_active: true,
                sort_order: 3,
            },
        ],
        reviews: [
            {
                athlete_email: 'ngoc.run@demo.com',
                rating: 5,
                comment: 'Mang đi long run hoặc buổi sauna đều hợp. Vị berry dễ uống hơn nhiều loại điện giải khác.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'adjustable-kettlebell-flex-series',
        seller_email: 'an.forge@demo.com',
        category_slug: 'free-weights',
        title: 'Adjustable Kettlebell Flex Series',
        description: 'Kettlebell chỉnh mức tạ dành cho home gym hoặc studio nhỏ. Chuyển nhanh giữa các mức tạ để gom nhiều bài vào một thiết bị, phù hợp cho swing, goblet squat, carry và circuit training.',
        product_type: 'physical',
        price: 2890000,
        compare_at_price: 3490000,
        currency: 'VND',
        stock_quantity: 24,
        track_inventory: true,
        sku: 'FHP-KB-FLEX',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80&sat=-15',
        gallery: [
            'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
            'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
            'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        ],
        attributes: {
            'Cơ chế': 'Dial adjust',
            'Ứng dụng': 'Swing, squat, carry, conditioning',
            'Phù hợp': 'Home gym, PT studio, apartment setup',
            'Tay cầm': 'Powder coat chống trượt nhẹ',
            'Bảo hành': '12 tháng',
        },
        tags: ['kettlebell', 'home gym', 'adjustable', 'strength'],
        view_count: 810,
        sale_count: 27,
        wishlist_count: 34,
        featured_weight: 72,
        variants: [
            {
                variant_label: '8–16kg',
                variant_attributes: { range: '8–16kg', use_case: 'Beginner / studio' },
                price: 2890000,
                compare_at_price: 3490000,
                stock_quantity: 8,
                sku: 'FHP-KB-816',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80&sat=-15',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: '8–24kg',
                variant_attributes: { range: '8–24kg', use_case: 'Most versatile' },
                price: 3490000,
                compare_at_price: 4090000,
                stock_quantity: 9,
                sku: 'FHP-KB-824',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: '12–32kg',
                variant_attributes: { range: '12–32kg', use_case: 'Advanced / strength bias' },
                price: 4290000,
                compare_at_price: 4890000,
                stock_quantity: 7,
                sku: 'FHP-KB-1232',
                image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'tam.cut@demo.com',
                rating: 4,
                comment: 'Bản 8–24kg đủ để chơi nhiều bài home gym. Cơ chế chỉnh tạ nhanh hơn mình nghĩ.',
                quality_rating: 4,
                value_rating: 4,
                delivery_rating: 4,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'resistance-band-progression-kit',
        seller_email: 'hoang.cali@demo.com',
        category_slug: 'functional-tools',
        title: 'Resistance Band Progression Kit',
        description: 'Combo band cho mobility, activation và pull-up progression. Có guide màu rõ, cường lực tách lớp hợp lý để dùng cho warm-up hoặc bodyweight progression dài hạn.',
        product_type: 'physical',
        price: 360000,
        compare_at_price: 450000,
        currency: 'VND',
        stock_quantity: 92,
        track_inventory: true,
        sku: 'HCL-BAND-KIT',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
            'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=1200&q=80&sat=-20',
            'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80',
        ],
        attributes: {
            'Mục đích': 'Warm-up, activation, mobility, pull-up progression',
            'Chất liệu': 'Natural latex blend',
            'Bản band': 'Mini band + loop band tùy variant',
            'Phù hợp': 'Beginner đến advanced',
            'Kèm theo': 'Quick start card',
        },
        tags: ['band set', 'mobility', 'pull up progression', 'functional'],
        view_count: 720,
        sale_count: 69,
        wishlist_count: 36,
        featured_weight: 77,
        variants: [
            {
                variant_label: 'Mini Band Starter',
                variant_attributes: { contents: '3 mini band', use_case: 'Activation + warm-up' },
                price: 360000,
                compare_at_price: 450000,
                stock_quantity: 29,
                sku: 'HCL-BAND-MINI',
                image_url: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Full Progression · 5 bands',
                variant_attributes: { contents: '5 loop band', use_case: 'Strength + mobility' },
                price: 520000,
                compare_at_price: 620000,
                stock_quantity: 24,
                sku: 'HCL-BAND-FULL',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Pull-up Assist Combo',
                variant_attributes: { contents: '3 loop band + door anchor', use_case: 'Bodyweight progression' },
                price: 610000,
                compare_at_price: 730000,
                stock_quantity: 20,
                sku: 'HCL-BAND-PULLUP',
                image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'tuan.vp@demo.com',
                rating: 5,
                comment: 'Combo pull-up assist rất hợp cho người mới. Band đủ lực và không bị mùi cao su quá nặng.',
                quality_rating: 5,
                value_rating: 5,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'recovery-massage-gun-pro',
        seller_email: 'reset.recovery@demo.com',
        category_slug: 'recovery-tools',
        title: 'Recovery Massage Gun Pro',
        description: 'Massage gun thiên về recovery sau buổi tập hoặc sau ngày ngồi lâu. Công suất vừa đủ, đầu súng đa dạng và độ ồn thấp hơn các bản phổ thông cùng tầm giá.',
        product_type: 'physical',
        price: 1590000,
        compare_at_price: 1890000,
        currency: 'VND',
        stock_quantity: 36,
        track_inventory: true,
        sku: 'RRS-GUN-PRO',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&q=80',
            'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1200&q=80',
            'https://images.unsplash.com/photo-1571902258032-78a167d6742c?w=1200&q=80',
        ],
        attributes: {
            'Mức tốc độ': '5 level',
            'Pin': '4-6 giờ sử dụng',
            'Độ ồn': 'Dưới 55 dB',
            'Đi kèm': '4 đầu súng + case mềm',
            'Ứng dụng': 'Recovery sau tập, thư giãn vùng vai cổ lưng',
        },
        tags: ['massage gun', 'recovery', 'mobility', 'post workout'],
        view_count: 940,
        sale_count: 53,
        wishlist_count: 42,
        featured_weight: 81,
        variants: [
            {
                variant_label: 'Mini',
                variant_attributes: { size: 'Mini', battery: '3 giờ', heads: '3 đầu súng' },
                price: 1590000,
                compare_at_price: 1890000,
                stock_quantity: 12,
                sku: 'RRS-GUN-MINI',
                image_url: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Standard',
                variant_attributes: { size: 'Standard', battery: '4 giờ', heads: '4 đầu súng' },
                price: 1890000,
                compare_at_price: 2190000,
                stock_quantity: 13,
                sku: 'RRS-GUN-STD',
                image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Pro Kit',
                variant_attributes: { size: 'Pro', battery: '6 giờ', heads: '6 đầu súng + case cứng' },
                price: 2490000,
                compare_at_price: 2890000,
                stock_quantity: 11,
                sku: 'RRS-GUN-PROKIT',
                image_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'tam.cut@demo.com',
                rating: 5,
                comment: 'Độ ồn thấp hơn mình nghĩ và đầu bullet dùng rất ổn cho mông đùi sau buổi chân.',
                quality_rating: 5,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'coach-pt-starter-pack-10',
        seller_email: 'david.ng@demo.com',
        category_slug: 'pt-sessions',
        title: 'Coach PT Starter Pack 10',
        description: 'Gói PT 1-1 cho người muốn sửa form, xây nền tảng strength hoặc body recomposition trong 6-8 tuần đầu. Có assessment đầu vào, chụp posture, video form và guideline bài tập về nhà.',
        product_type: 'service',
        price: 4500000,
        compare_at_price: 5200000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'DPS-PT-10',
        digital_file_url: null,
        preview_content: 'Bao gồm assessment, 10 buổi PT, 1 logbook cơ bản và guideline bài tập tự tập giữa tuần.',
        thumbnail_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1200&q=80',
            'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80',
            'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1200&q=80',
        ],
        attributes: {
            'Format': '1-1 offline',
            'Phù hợp': 'Beginner đến intermediate',
            'Thời hạn sử dụng': '60 ngày kể từ buổi đầu',
            'Bao gồm': 'Assessment, video form, logbook cơ bản',
            'Địa điểm': 'TP. Hồ Chí Minh, lịch hẹn trước',
        },
        tags: ['pt', 'coaching', 'offline', 'form correction'],
        view_count: 760,
        sale_count: 32,
        wishlist_count: 24,
        featured_weight: 86,
        variants: [
            {
                variant_label: '5 sessions',
                variant_attributes: { sessions: '5', format: '1-1 offline', validity: '30 ngày' },
                price: 2500000,
                compare_at_price: 2950000,
                stock_quantity: null,
                sku: 'DPS-PT-5',
                image_url: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: '10 sessions',
                variant_attributes: { sessions: '10', format: '1-1 offline', validity: '60 ngày' },
                price: 4500000,
                compare_at_price: 5200000,
                stock_quantity: null,
                sku: 'DPS-PT-10',
                image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: '20 sessions + remote check-in',
                variant_attributes: { sessions: '20', format: '1-1 offline + online', validity: '90 ngày' },
                price: 8200000,
                compare_at_price: 9300000,
                stock_quantity: null,
                sku: 'DPS-PT-20',
                image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'hau.gym@demo.com',
                rating: 5,
                comment: 'Assessment đầu vào rất kỹ. Chỉ sau vài buổi squat và hinge mình thấy tự tin hơn nhiều.',
                quality_rating: 5,
                value_rating: 4,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'hybrid-fitness-summit-2026-ticket',
        seller_email: 'huong.crossfit@demo.com',
        category_slug: 'event-tickets',
        title: 'Hybrid Fitness Summit 2026 Ticket',
        description: 'Vé tham dự summit 1 ngày với workshop strength, hybrid endurance, recovery protocol và networking cùng coach, gym owner, athlete community trên GYMERVIET.',
        product_type: 'service',
        price: 790000,
        compare_at_price: 990000,
        currency: 'VND',
        stock_quantity: 180,
        track_inventory: true,
        sku: 'HHP-SUMMIT-2026',
        digital_file_url: 'https://downloads.gymerviet.demo/products/hybrid-fitness-summit-2026-ticket.pdf',
        preview_content: 'Một ngày gồm 4 workshop, 1 panel discussion, 1 networking session và goodie bag cho khách check-in sớm.',
        thumbnail_url: 'https://images.unsplash.com/photo-1518600506278-4e8ef466b810?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=1200&q=80',
            'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80',
            'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&q=80',
        ],
        attributes: {
            'Địa điểm': 'TP. Hồ Chí Minh',
            'Thời lượng': '1 ngày · 08:30–18:00',
            'Bao gồm': 'Workshop, panel, goodie bag, e-certificate',
            'Phù hợp': 'Coach, athlete, gym owner, creator',
            'Check-in': 'QR ticket gửi qua email sau thanh toán',
        },
        tags: ['event', 'workshop', 'networking', 'hybrid fitness'],
        view_count: 620,
        sale_count: 57,
        wishlist_count: 47,
        featured_weight: 83,
        variants: [
            {
                variant_label: 'Early Bird',
                variant_attributes: { access: 'Standard', bonus: 'Goodie bag', seat: 'General' },
                price: 790000,
                compare_at_price: 990000,
                stock_quantity: 60,
                sku: 'HHP-SUMMIT-EARLY',
                image_url: 'https://images.unsplash.com/photo-1518600506278-4e8ef466b810?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Standard',
                variant_attributes: { access: 'Standard', bonus: 'E-certificate', seat: 'General' },
                price: 990000,
                compare_at_price: 1190000,
                stock_quantity: 80,
                sku: 'HHP-SUMMIT-STD',
                image_url: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'VIP + backstage meet',
                variant_attributes: { access: 'VIP', bonus: 'Priority seating + backstage', seat: 'Front row' },
                price: 1690000,
                compare_at_price: 1990000,
                stock_quantity: 40,
                sku: 'HHP-SUMMIT-VIP',
                image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'khoa.demo@demo.com',
                rating: 5,
                comment: 'Năm trước đi workshop của Hương rất đáng tiền nên thấy combo summit này hấp dẫn. Lịch nội dung khá thực chiến.',
                quality_rating: 5,
                value_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'lotus-flow-unlimited-membership',
        seller_email: 'thao.lotus@demo.com',
        category_slug: 'gym-memberships',
        title: 'Lotus Flow Unlimited Membership',
        description: 'Membership studio yoga với lịch class mềm, teacher quality cao và không gian yên. Phù hợp cho người muốn duy trì practice đều 3-5 buổi mỗi tuần, kèm trial reformer hoặc breathwork tùy gói.',
        product_type: 'service',
        price: 1890000,
        compare_at_price: 2300000,
        currency: 'VND',
        stock_quantity: null,
        track_inventory: false,
        sku: 'LFB-MEMBER-UNL',
        digital_file_url: null,
        preview_content: 'Membership kích hoạt theo tháng, đặt lịch class trên app và có 1 buổi orientation dành cho học viên mới.',
        thumbnail_url: 'https://images.unsplash.com/photo-1545208393-596371ba4d31?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=1200&q=80',
            'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&q=80',
            'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&q=80',
        ],
        attributes: {
            'Loại hình': 'Studio membership',
            'Hiệu lực': '30 ngày',
            'Đặt lịch': 'App / web booking',
            'Bao gồm': 'Orientation, community class, access workshop ưu đãi',
            'Địa điểm': 'Lotus Flow studio, TP. Hồ Chí Minh',
        },
        tags: ['membership', 'yoga studio', 'wellness', 'unlimited class'],
        view_count: 880,
        sale_count: 39,
        wishlist_count: 52,
        featured_weight: 87,
        variants: [
            {
                variant_label: '8 classes / month',
                variant_attributes: { access: '8 classes', validity: '30 ngày', extras: 'Orientation' },
                price: 1290000,
                compare_at_price: 1490000,
                stock_quantity: null,
                sku: 'LFB-MEMBER-8',
                image_url: 'https://images.unsplash.com/photo-1545208393-596371ba4d31?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: 'Unlimited',
                variant_attributes: { access: 'Unlimited', validity: '30 ngày', extras: 'Priority booking' },
                price: 1890000,
                compare_at_price: 2300000,
                stock_quantity: null,
                sku: 'LFB-MEMBER-UNL',
                image_url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Unlimited + Reformer Trial',
                variant_attributes: { access: 'Unlimited', validity: '30 ngày', extras: '2 reformer trial class' },
                price: 2390000,
                compare_at_price: 2790000,
                stock_quantity: null,
                sku: 'LFB-MEMBER-UNL-REF',
                image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'an.yoga@demo.com',
                rating: 5,
                comment: 'Nếu muốn đi class đều và không gian yên thì gói unlimited rất đáng. Giá cao hơn nhưng teacher quality ổn.',
                quality_rating: 5,
                value_rating: 4,
                is_verified_purchase: true,
            },
        ],
    },
    {
        slug: 'magnesium-recovery-balm-night-reset',
        seller_email: 'reset.recovery@demo.com',
        category_slug: 'body-care',
        title: 'Magnesium Recovery Balm Night Reset',
        description: 'Body balm mùi thảo mộc dịu, texture không quá bết và phù hợp massage vùng vai gáy, bắp chân hoặc lưng dưới sau ngày dài. Dùng tốt trước khi ngủ hoặc sau buổi recovery.',
        product_type: 'physical',
        price: 240000,
        compare_at_price: 290000,
        currency: 'VND',
        stock_quantity: 78,
        track_inventory: true,
        sku: 'RRS-BALM-MAG',
        digital_file_url: null,
        preview_content: null,
        thumbnail_url: 'https://images.unsplash.com/photo-1556228578-dd6e4b9f1f31?w=1200&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&q=80',
            'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1200&q=80',
            'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&q=80',
        ],
        attributes: {
            'Dung tích': '50ml / 100ml',
            'Mùi hương': 'Herbal calm',
            'Cảm giác': 'Thấm nhanh, không quá bóng',
            'Dùng cho': 'Vai gáy, bắp chân, lưng dưới, cẳng tay',
            'Không chứa': 'Paraben, mineral oil',
        },
        tags: ['body care', 'magnesium balm', 'recovery', 'sleep'],
        view_count: 710,
        sale_count: 55,
        wishlist_count: 34,
        featured_weight: 75,
        variants: [
            {
                variant_label: '50ml',
                variant_attributes: { size: '50ml', use_case: 'Travel / thử trước' },
                price: 240000,
                compare_at_price: 290000,
                stock_quantity: 28,
                sku: 'RRS-BALM-50',
                image_url: 'https://images.unsplash.com/photo-1556228578-dd6e4b9f1f31?w=800&q=80',
                is_active: true,
                sort_order: 0,
            },
            {
                variant_label: '100ml',
                variant_attributes: { size: '100ml', use_case: 'Dùng hằng ngày' },
                price: 390000,
                compare_at_price: 460000,
                stock_quantity: 26,
                sku: 'RRS-BALM-100',
                image_url: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80',
                is_active: true,
                sort_order: 1,
            },
            {
                variant_label: 'Duo Kit',
                variant_attributes: { size: '50ml x2', use_case: 'Một ở nhà, một ở túi gym' },
                price: 440000,
                compare_at_price: 520000,
                stock_quantity: 24,
                sku: 'RRS-BALM-DUO',
                image_url: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80',
                is_active: true,
                sort_order: 2,
            },
        ],
        reviews: [
            {
                athlete_email: 'an.yoga@demo.com',
                rating: 4,
                comment: 'Mùi dễ chịu và thấm nhanh. Mình hay dùng bắp chân sau đi bộ nhiều hoặc sau class flow dài.',
                quality_rating: 4,
                value_rating: 4,
                delivery_rating: 5,
                is_verified_purchase: true,
            },
        ],
    },
];
